# docker-compose.yml
version: "3"
services:
  back:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/back
      - /back/node_modules

  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hypertube
      POSTGRES_INITDB_WALDIR: /var/lib/postgresql/data
    volumes:
    - ./tmp/db:/var/lib/postgresql/data

volumes:
    back:
    postgres:
